name: 'Deploy to Dokku'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@main
        with:
          git_remote_url: 'ssh://dokku@207.180.247.39:22/shevchenko'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
